import { Button, NewIcon } from '../../main'
import s from './ButtonsPage.module.scss'

export const ButtonsPage = () => {
	return (
		<div className={s.root}>
			<div className={s.clearButton}>
				<h2>Варианты</h2>
				<div className={s.buttonsWrapper}>
					<Button
						as='button'
						variant='blue'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='gray'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteStroke'
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteFilled'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='sokolniki'
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='black'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='volodiyaLight'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='shade'>
						Приветики
					</Button>
				</div>
			</div>
			<div className={s.preButton}>
				<h2>Иконки пре</h2>
				<div className={s.buttonsWrapper}>
					<Button
						as='button'
						variant='blue'
						pre={
							<NewIcon
								name={'filter'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='gray'
						pre={
							<NewIcon
								name={'ruble'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteStroke'
						pre={
							<NewIcon
								name={'walk'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteFilled'
						pre={
							<NewIcon
								name={'burger'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='sokolniki'
						pre={
							<NewIcon
								name={'directionDown'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='black'
						pre={
							<NewIcon
								name={'car'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='volodiyaLight'
						pre={
							<NewIcon
								name={'star'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='shade'
						pre={
							<NewIcon
								name={'minus'}
								size='20'
							/>
						}>
						Приветики
					</Button>
				</div>
			</div>
			<div className={s.preButton}>
				<h2>Иконки пост</h2>
				<div className={s.buttonsWrapper}>
					<Button
						as='button'
						variant='blue'
						post={
							<NewIcon
								name={'filter'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='gray'
						post={
							<NewIcon
								name={'ruble'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteStroke'
						post={
							<NewIcon
								name={'walk'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteFilled'
						post={
							<NewIcon
								name={'burger'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='sokolniki'
						post={
							<NewIcon
								name={'directionDown'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='black'
						post={
							<NewIcon
								name={'car'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='volodiyaLight'
						post={
							<NewIcon
								name={'star'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='shade'
						post={
							<NewIcon
								name={'minus'}
								size='20'
							/>
						}>
						Приветики
					</Button>
				</div>
			</div>
			<div className={s.bothButton}>
				<h2>Иконки пре и пост</h2>
				<div className={s.buttonsWrapper}>
					<Button
						as='button'
						variant='blue'
						pre={
							<NewIcon
								name={'filter'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'filter'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='gray'
						pre={
							<NewIcon
								name={'ruble'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'ruble'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteStroke'
						pre={
							<NewIcon
								name={'walk'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'walk'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteFilled'
						pre={
							<NewIcon
								name={'burger'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'burger'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='sokolniki'
						pre={
							<NewIcon
								name={'directionDown'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'directionDown'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='black'
						pre={
							<NewIcon
								name={'car'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'car'}
								size='20'
							/>
						}>
						Приветики
					</Button>
					<Button
						as='button'
						variant='volodiyaLight'
						pre={
							<NewIcon
								name={'star'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'star'}
								size='20'
							/>
						}
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='shade'
						pre={
							<NewIcon
								name={'minus'}
								size='20'
							/>
						}
						post={
							<NewIcon
								name={'minus'}
								size='20'
							/>
						}>
						Приветики
					</Button>
				</div>
			</div>
			<div className={s.loaderButton}>
				<h2>Иконки лоадер</h2>
				<div className={s.buttonsWrapper}>
					<Button
						as='button'
						variant='blue'
						isLoading
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='gray'
						isLoading
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteStroke'
						isLoading>
						Приветики
					</Button>
					<Button
						as='button'
						variant='whiteFilled'
						isLoading>
						Приветики
					</Button>
					<Button
						as='button'
						variant='sokolniki'
						isLoading>
						Приветики
					</Button>
					<Button
						as='button'
						variant='black'
						isLoading
						width='full'>
						Приветики
					</Button>
					<Button
						as='button'
						variant='volodiyaLight'
						isLoading>
						Приветики
					</Button>
					<Button
						as='button'
						variant='shade'
						isLoading>
						Приветики
					</Button>
				</div>
			</div>
		</div>
	)
}

